/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class fuji_itemConstants {

  public static final java.lang.String LANGUAGE_JA = "JA";

  public static final java.lang.String LANGUAGE_EN = "EN";

}
