/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (1.0.0-dev)", date = "2017-12-02")
public class ItemOption implements org.apache.thrift.TBase<ItemOption, ItemOption._Fields>, java.io.Serializable, Cloneable, Comparable<ItemOption> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ItemOption");

  private static final org.apache.thrift.protocol.TField WITH_LANGUAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("withLanguage", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField WITH_ICON_FIELD_DESC = new org.apache.thrift.protocol.TField("withIcon", org.apache.thrift.protocol.TType.BOOL, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ItemOptionStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ItemOptionTupleSchemeFactory();

  public boolean withLanguage; // optional
  public boolean withIcon; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    WITH_LANGUAGE((short)1, "withLanguage"),
    WITH_ICON((short)2, "withIcon");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // WITH_LANGUAGE
          return WITH_LANGUAGE;
        case 2: // WITH_ICON
          return WITH_ICON;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __WITHLANGUAGE_ISSET_ID = 0;
  private static final int __WITHICON_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.WITH_LANGUAGE,_Fields.WITH_ICON};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.WITH_LANGUAGE, new org.apache.thrift.meta_data.FieldMetaData("withLanguage", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.WITH_ICON, new org.apache.thrift.meta_data.FieldMetaData("withIcon", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ItemOption.class, metaDataMap);
  }

  public ItemOption() {
    this.withLanguage = false;

    this.withIcon = false;

  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ItemOption(ItemOption other) {
    __isset_bitfield = other.__isset_bitfield;
    this.withLanguage = other.withLanguage;
    this.withIcon = other.withIcon;
  }

  public ItemOption deepCopy() {
    return new ItemOption(this);
  }

  @Override
  public void clear() {
    this.withLanguage = false;

    this.withIcon = false;

  }

  public boolean isWithLanguage() {
    return this.withLanguage;
  }

  public ItemOption setWithLanguage(boolean withLanguage) {
    this.withLanguage = withLanguage;
    setWithLanguageIsSet(true);
    return this;
  }

  public void unsetWithLanguage() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __WITHLANGUAGE_ISSET_ID);
  }

  /** Returns true if field withLanguage is set (has been assigned a value) and false otherwise */
  public boolean isSetWithLanguage() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __WITHLANGUAGE_ISSET_ID);
  }

  public void setWithLanguageIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __WITHLANGUAGE_ISSET_ID, value);
  }

  public boolean isWithIcon() {
    return this.withIcon;
  }

  public ItemOption setWithIcon(boolean withIcon) {
    this.withIcon = withIcon;
    setWithIconIsSet(true);
    return this;
  }

  public void unsetWithIcon() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __WITHICON_ISSET_ID);
  }

  /** Returns true if field withIcon is set (has been assigned a value) and false otherwise */
  public boolean isSetWithIcon() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __WITHICON_ISSET_ID);
  }

  public void setWithIconIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __WITHICON_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case WITH_LANGUAGE:
      if (value == null) {
        unsetWithLanguage();
      } else {
        setWithLanguage((java.lang.Boolean)value);
      }
      break;

    case WITH_ICON:
      if (value == null) {
        unsetWithIcon();
      } else {
        setWithIcon((java.lang.Boolean)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case WITH_LANGUAGE:
      return isWithLanguage();

    case WITH_ICON:
      return isWithIcon();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case WITH_LANGUAGE:
      return isSetWithLanguage();
    case WITH_ICON:
      return isSetWithIcon();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof ItemOption)
      return this.equals((ItemOption)that);
    return false;
  }

  public boolean equals(ItemOption that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_withLanguage = true && this.isSetWithLanguage();
    boolean that_present_withLanguage = true && that.isSetWithLanguage();
    if (this_present_withLanguage || that_present_withLanguage) {
      if (!(this_present_withLanguage && that_present_withLanguage))
        return false;
      if (this.withLanguage != that.withLanguage)
        return false;
    }

    boolean this_present_withIcon = true && this.isSetWithIcon();
    boolean that_present_withIcon = true && that.isSetWithIcon();
    if (this_present_withIcon || that_present_withIcon) {
      if (!(this_present_withIcon && that_present_withIcon))
        return false;
      if (this.withIcon != that.withIcon)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetWithLanguage()) ? 131071 : 524287);
    if (isSetWithLanguage())
      hashCode = hashCode * 8191 + ((withLanguage) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetWithIcon()) ? 131071 : 524287);
    if (isSetWithIcon())
      hashCode = hashCode * 8191 + ((withIcon) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(ItemOption other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetWithLanguage()).compareTo(other.isSetWithLanguage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWithLanguage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.withLanguage, other.withLanguage);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetWithIcon()).compareTo(other.isSetWithIcon());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWithIcon()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.withIcon, other.withIcon);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ItemOption(");
    boolean first = true;

    if (isSetWithLanguage()) {
      sb.append("withLanguage:");
      sb.append(this.withLanguage);
      first = false;
    }
    if (isSetWithIcon()) {
      if (!first) sb.append(", ");
      sb.append("withIcon:");
      sb.append(this.withIcon);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ItemOptionStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ItemOptionStandardScheme getScheme() {
      return new ItemOptionStandardScheme();
    }
  }

  private static class ItemOptionStandardScheme extends org.apache.thrift.scheme.StandardScheme<ItemOption> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ItemOption struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // WITH_LANGUAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.withLanguage = iprot.readBool();
              struct.setWithLanguageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // WITH_ICON
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.withIcon = iprot.readBool();
              struct.setWithIconIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ItemOption struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetWithLanguage()) {
        oprot.writeFieldBegin(WITH_LANGUAGE_FIELD_DESC);
        oprot.writeBool(struct.withLanguage);
        oprot.writeFieldEnd();
      }
      if (struct.isSetWithIcon()) {
        oprot.writeFieldBegin(WITH_ICON_FIELD_DESC);
        oprot.writeBool(struct.withIcon);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ItemOptionTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ItemOptionTupleScheme getScheme() {
      return new ItemOptionTupleScheme();
    }
  }

  private static class ItemOptionTupleScheme extends org.apache.thrift.scheme.TupleScheme<ItemOption> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ItemOption struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetWithLanguage()) {
        optionals.set(0);
      }
      if (struct.isSetWithIcon()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetWithLanguage()) {
        oprot.writeBool(struct.withLanguage);
      }
      if (struct.isSetWithIcon()) {
        oprot.writeBool(struct.withIcon);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ItemOption struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.withLanguage = iprot.readBool();
        struct.setWithLanguageIsSet(true);
      }
      if (incoming.get(1)) {
        struct.withIcon = iprot.readBool();
        struct.setWithIconIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

