/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef fuji_CONSTANTS_H
#define fuji_CONSTANTS_H

#include "fuji_types.h"



class fujiConstants {
 public:
  fujiConstants();

};

extern const fujiConstants g_fuji_constants;



#endif
