/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "fuji_constants.h"



const fujiConstants g_fuji_constants;

fujiConstants::fujiConstants() {
}



