/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "fuji.item_constants.h"



const fuji.itemConstants g_fuji.item_constants;

fuji.itemConstants::fuji.itemConstants() {
}



