/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef fuji.item_CONSTANTS_H
#define fuji.item_CONSTANTS_H

#include "fuji.item_types.h"



class fuji.itemConstants {
 public:
  fuji.itemConstants();

};

extern const fuji.itemConstants g_fuji.item_constants;



#endif
